### ISSUE TITLE
Galactica is producing output errors: [RoleGuard] Role mismatch. Expected admin. Actual user

### ISSUE THREAD

**Issue by alfydev** [verity-team/galactica#26]
[Nest] 3650465  - 01/08/2024, 8:59:46 PM   ERROR [RoleGuard] Role mismatch. Expected admin. Actual user
[Nest] 3650465  - 01/08/2024, 8:59:46 PM     LOG POST /auth/verify/admin: FAILED 403. 2.63 ms
[Nest] 3650465  - 01/08/2024, 8:59:46 PM     LOG POST /auth/verify/admin: REQUEST
[Nest] 3650465  - 01/08/2024, 8:59:46 PM   ERROR [RoleGuard] Role mismatch. Expected admin. Actual user
[Nest] 3650465  - 01/08/2024, 8:59:46 PM     LOG POST /auth/verify/admin: FAILED 403. 1.99 ms
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/preview: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/preview: OK - 1.25 ms
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/preview: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/preview: OK - 0.66 ms
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG POST /auth/verify/user: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG POST /auth/verify/user: OK - 3.05 ms
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG POST /auth/verify/user: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG POST /auth/verify/user: OK - 2.10 ms
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/latest?offset=0&limit=5&status=APPROVED: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:10 PM     LOG GET /meme/latest?offset=0&limit=5&status=APPROVED: OK - 73.91 ms
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG POST /auth/verify/user: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG POST /auth/verify/user: OK - 2.61 ms
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG POST /auth/verify/user: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG POST /auth/verify/user: OK - 1.60 ms
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG GET /meme/latest?offset=0&limit=5&status=APPROVED: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:17 PM     LOG GET /meme/latest?offset=0&limit=5&status=APPROVED: OK - 5.86 ms
[Nest] 3650465  - 01/08/2024, 9:02:37 PM     LOG POST /auth/verify/admin: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:37 PM   ERROR [RoleGuard] Role mismatch. Expected admin. Actual user
[Nest] 3650465  - 01/08/2024, 9:02:37 PM     LOG POST /auth/verify/admin: FAILED 403. 2.43 ms
[Nest] 3650465  - 01/08/2024, 9:02:37 PM     LOG POST /auth/verify/admin: REQUEST
[Nest] 3650465  - 01/08/2024, 9:02:37 PM   ERROR [RoleGuard] Role mismatch. Expected admin. Actual user
[Nest] 3650465  - 01/08/2024, 9:02:37 PM     LOG POST /auth/verify/admin: FAILED 403. 2.05 ms

**Comment by GiveMeSomething** [comment]
@alfydev Can I have some more context on this one.

This error is logged when there are user trying to use admin's endpoints when they are using an user's access token
